"""branch index lifecycle: created_at, nullable head_sha

Revision ID: 84829fb72d49
Revises: 5844b79def63
Create Date: 2026-09-21 02:36:27.802907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84829fb72d49'
down_revision: Union[str, None] = '5844b79def63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branch_index', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('branch_index', 'head_sha',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)
    op.create_index('ix_branch_index_repo_branch_created', 'branch_index', ['repo_id', 'branch_name', 'created_at'], unique=False)
    op.add_column('index_update_log', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('index_update_log', 'created_at')
    op.drop_index('ix_branch_index_repo_branch_created', table_name='branch_index')
    op.alter_column('branch_index', 'head_sha',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
    op.drop_column('branch_index', 'created_at')
    # ### end Alembic commands ###
