"""github app integration

Revision ID: 86bf719221ef
Revises: 84829fb72d49
Create Date: 2026-10-07 04:01:57.917323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86bf719221ef'
down_revision: Union[str, None] = '84829fb72d49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_deliveries',
    sa.Column('delivery_id', sa.String(length=64), nullable=False),
    sa.Column('event', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('delivery_id')
    )
    op.add_column('analysis_runs', sa.Column('diff_text', sa.Text(), nullable=True))
    op.add_column('analysis_runs', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # server_default backfills any pre-existing rows; the ORM sets it explicitly.
    op.add_column('github_installations', sa.Column('account_type', sa.String(length=32), server_default='User', nullable=False))
    op.alter_column('github_installations', 'installation_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.create_unique_constraint('uq_pull_requests_repo_number', 'pull_requests', ['repo_id', 'number'])
    op.add_column('repositories', sa.Column('github_repo_id', sa.BigInteger(), nullable=True))
    op.add_column('repositories', sa.Column('auto_review_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # Named explicitly (Postgres's own default name) so downgrade can drop it.
    op.create_unique_constraint('repositories_github_repo_id_key', 'repositories', ['github_repo_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('repositories_github_repo_id_key', 'repositories', type_='unique')
    op.drop_column('repositories', 'auto_review_enabled')
    op.drop_column('repositories', 'github_repo_id')
    op.drop_constraint('uq_pull_requests_repo_number', 'pull_requests', type_='unique')
    op.alter_column('github_installations', 'installation_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('github_installations', 'account_type')
    op.drop_column('analysis_runs', 'created_at')
    op.drop_column('analysis_runs', 'diff_text')
    op.drop_table('webhook_deliveries')
    # ### end Alembic commands ###
