"""github app credentials

Revision ID: a0b68475a72c
Revises: 86bf719221ef
Create Date: 2026-10-07 05:29:19.962423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0b68475a72c'
down_revision: Union[str, None] = '86bf719221ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('github_app_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.BigInteger(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('owner_login', sa.String(length=255), nullable=False),
    sa.Column('html_url', sa.String(length=500), nullable=False),
    sa.Column('client_id', sa.String(length=100), nullable=False),
    sa.Column('client_secret_enc', sa.Text(), nullable=False),
    sa.Column('webhook_secret_enc', sa.Text(), nullable=False),
    sa.Column('private_key_enc', sa.Text(), nullable=False),
    sa.Column('webhook_proxy_url', sa.String(length=500), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('id = 1', name='ck_github_app_credentials_singleton'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('github_app_credentials')
    # ### end Alembic commands ###
